language: node_js
node_js:
  - "0.12"
  - "0.10"
before_install:
  - npm install -g grunt-cli istanbul coveralls mocha
script:
  - npm test --verbose
after_success:
  - cat ./coverage/lcov.info | coveralls && rm -rf ./coverage

