language: node_js
node_js:
  - "0.12"
before_install:
  - npm install -g istanbul coveralls
script:
  - npm test --verbose
after_success:
  - cat ./coverage/lcov.info | coveralls && rm -rf ./coverage

