language: node_js
node_js:
  - "0.12"
  - "0.10"
before_install:
  - npm install -g istanbul coveralls mocha
script:
  - npm test ./spec/src/**/* --verbose
after_success:
  - cat ./coverage/lcov.info | coveralls && rm -rf ./coverage

